# Generated by Django 2.0.6 on 2018-06-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师名字')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名字')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级名字')),
                ('room_name', models.CharField(max_length=100, verbose_name='教室名')),
                ('week', models.CharField(max_length=10, verbose_name='星期几')),
                ('order', models.CharField(max_length=5, verbose_name='第几节')),
            ],
        ),
    ]
