# Generated by Django 2.0.6 on 2018-06-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='schedule',
            index_together={('week', 'order')},
        ),
    ]
