# Generated by Django 2.0.6 on 2018-07-08 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任课教师'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='banji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Banji', verbose_name='班级'),
        ),
    ]
