# Generated by Django 2.0.6 on 2018-07-08 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180708_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='banji',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
