# Generated by Django 2.0.6 on 2018-07-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_banji_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动题目')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='开展时间')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=10, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(max_length=4, verbose_name='性别')),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Act')),
                ('banji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Banji')),
            ],
        ),
    ]
