# Generated by Django 2.0.6 on 2018-07-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_act_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='banji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Banji'),
        ),
    ]
