# Generated by Django 2.0.6 on 2018-07-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20180709_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='课程封面图')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course_name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Course'),
        ),
    ]
