# Generated by Django 2.0.6 on 2018-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20180709_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
