# Generated by Django 2.0.6 on 2018-07-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_act_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='act',
        ),
        migrations.AddField(
            model_name='act',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Student'),
        ),
    ]
