# Generated by Django 2.0.6 on 2018-07-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20180712_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='act',
            name='banji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Banji'),
        ),
    ]
